// Regenerates public/sitemap.xml from the live route list on every build —
// runs BEFORE `vite build` so the fresh file gets copied into dist/ along
// with the rest of public/. Do not hand-edit sitemap.xml, it will be
// overwritten; edit src/data/products.ts or scripts/routes.mjs instead.
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { LANGS, DEFAULT_LANG, allPages } from "./routes.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SITE_URL = "https://mipador.com";
const today = new Date().toISOString().slice(0, 10);

function escapeXml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function hreflangBlock(path) {
  const alts = LANGS.map(
    (l) => `    <xhtml:link rel="alternate" hreflang="${l}" href="${SITE_URL}/${l}/${path}" />`
  ).join("\n");
  const xdefault = `    <xhtml:link rel="alternate" hreflang="x-default" href="${SITE_URL}/${DEFAULT_LANG}/${path}" />`;
  return `${alts}\n${xdefault}`;
}

function urlEntry(lang, page) {
  const loc = `${SITE_URL}/${lang}/${page.path}`;
  const image = page.image
    ? `\n    <image:image>\n      <image:loc>${SITE_URL}${page.image}</image:loc>\n      <image:title>${escapeXml(page.imageTitle)}</image:title>\n    </image:image>`
    : "";
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
${hreflangBlock(page.path)}${image}
  </url>`;
}

const urls = [];
for (const page of allPages) {
  for (const lang of LANGS) {
    urls.push(urlEntry(lang, page));
  }
}

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Mipador Sitemap — https://mipador.com
  Auto-generated by scripts/generate-sitemap.mjs on every build.
  Do not hand-edit — it will be overwritten on the next build.
-->
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
>
${urls.join("\n\n")}
</urlset>
`;

writeFileSync(resolve(root, "public/sitemap.xml"), xml, "utf8");
console.log(
  `Generated sitemap.xml — ${allPages.length} pages × ${LANGS.length} languages = ${urls.length} URLs`
);
